[project]
name = "knowledge-distillation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "loguru>=0.7.3",
    "torch>=2.7.1",
    "transformers>=4.53.2",
]
